### ISSUE TITLE
Encountering error after removing member from a Group

### ISSUE THREAD

**Issue by Evang264** [cpinitiative/usaco-guide#3037]
I encountered this error after removing a person from Groups:
```
TypeError: Cannot read properties of undefined (reading 'uid')
    at Or (https://usaco.guide/component---src-pages-groups-tsx-611d396901b95fb3686b.js:1:135840)
    at main
    at div
    at div
    at div
    at o (https://usaco.guide/6db20d0c136a330f02a3c9eef22c0b1ead18f764-364de5b4d40babf80bdd.js:1:6966)
    at Ir (https://usaco.guide/component---src-pages-groups-tsx-611d396901b95fb3686b.js:1:138661)
    at yu (https://usaco.guide/component---src-pages-groups-tsx-611d396901b95fb3686b.js:1:284043)
    at div
    at t (https://usaco.guide/app-ee2f11a60cdc2ef7af01.js:2:257452)
    at F (https://usaco.guide/app-ee2f11a60cdc2ef7af01.js:2:257203)
    at t (https://usaco.guide/app-ee2f11a60cdc2ef7af01.js:2:256262)
    at A (https://usaco.guide/app-ee2f11a60cdc2ef7af01.js:2:254426)
    at U
    at xu (https://usaco.guide/component---src-pages-groups-tsx-611d396901b95fb3686b.js:1:282782)
    at div
    at t (https://usaco.guide/app-ee2f11a60cdc2ef7af01.js:2:257452)
    at F (https://usaco.guide/app-ee2f11a60cdc2ef7af01.js:2:257203)
    at t (https://usaco.guide/app-ee2f11a60cdc2ef7af01.js:2:256262)
    at A (https://usaco.guide/app-ee2f11a60cdc2ef7af01.js:2:254426)
    at U
    at qr (https://usaco.guide/component---src-pages-groups-tsx-611d396901b95fb3686b.js:1:146579)
    at Z (https://usaco.guide/component---src-pages-groups-tsx-611d396901b95fb3686b.js:1:29922)
    at g (https://usaco.guide/component---src-pages-groups-tsx-611d396901b95fb3686b.js:1:6860)
    at Eu
    at t (https://usaco.guide/app-ee2f11a60cdc2ef7af01.js:2:28672)
    at e
    at div
    at t (https://usaco.guide/app-ee2f11a60cdc2ef7af01.js:2:257452)
    at F (https://usaco.guide/app-ee2f11a60cdc2ef7af01.js:2:257203)
    at t (https://usaco.guide/app-ee2f11a60cdc2ef7af01.js:2:256262)
    at A (https://usaco.guide/app-ee2f11a60cdc2ef7af01.js:2:254426)
    at U
    at t (https://usaco.guide/app-ee2f11a60cdc2ef7af01.js:2:5832)
    at t (https://usaco.guide/app-ee2f11a60cdc2ef7af01.js:2:32052)
    at o (https://usaco.guide/app-ee2f11a60cdc2ef7af01.js:2:35293)
    at fe (https://usaco.guide/app-ee2f11a60cdc2ef7af01.js:2:605047)
    at c (https://usaco.guide/app-ee2f11a60cdc2ef7af01.js:2:247648)
    at g (https://usaco.guide/app-ee2f11a60cdc2ef7af01.js:2:149719)
    at a (https://usaco.guide/app-ee2f11a60cdc2ef7af01.js:2:135303)
    at a (https://usaco.guide/app-ee2f11a60cdc2ef7af01.js:2:242931)
    at ce (https://usaco.guide/app-ee2f11a60cdc2ef7af01.js:2:240313)
    at a (https://usaco.guide/app-ee2f11a60cdc2ef7af01.js:2:139875)
    at n (https://usaco.guide/app-ee2f11a60cdc2ef7af01.js:2:406808)
    at p (https://usaco.guide/app-ee2f11a60cdc2ef7af01.js:2:136288)
    at l (https://usaco.guide/app-ee2f11a60cdc2ef7af01.js:2:561004)
    at t (https://usaco.guide/app-ee2f11a60cdc2ef7af01.js:2:32717)
    at t (https://usaco.guide/app-ee2f11a60cdc2ef7af01.js:2:254566)
    at A (https://usaco.guide/app-ee2f11a60cdc2ef7af01.js:2:254426)
    at n (https://usaco.guide/app-ee2f11a60cdc2ef7af01.js:2:34832)
    at a (https://usaco.guide/app-ee2f11a60cdc2ef7af01.js:2:37072)
```
Reloading the page did not make this error go away.

**Comment by bqi343** [comment]
@Evang144 @maggie-j-liu was this resolved?

**Comment by maggie-j-liu** [comment]
no... the fix didn't work (but a workaround is to leave the page and go back)
